spring.application.name=pft
spring.datasource.url=jdbc:postgresql://localhost:5433/dbName
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true